services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20


  minio-init:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo '🔹 Configurando MinIO...' &&
      mc alias set local http://minio:9000 admin password &&
      echo '🔹 Criando buckets...' &&
      mc mb -p local/bronze || true &&
      mc mb -p local/silver || true &&
      mc mb -p local/gold   || true &&
      echo '🔹 Ativando versionamento...' &&
      mc version enable local/bronze || true &&
      mc version enable local/silver || true &&
      mc version enable local/gold   || true &&
      echo '🔹 Criando usuário teste...' &&
      mc admin user add local teste password &&
      mc admin policy attach local readwrite --user teste &&
      echo '✅ Setup completo!'
      "
  # trino:
  #   image: 'trinodb/trino:444'
  #   container_name: trino
  #   volumes:
  #     - ./etc/catalog:/etc/trino/catalog
  #   ports:
  #     - '8080:8080'


  # metastore:
  #   image: postgres:alpine3.19
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres-user
  #     - POSTGRES_PASSWORD=postgres-password
  #     - POSTGRES_DB=iceberg
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres-user -d iceberg"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  dremio:
      image: dremio/dremio-oss:24.1
      container_name: dremio
      platform: linux/amd64
      ports:  
        - 9047:9047 
        - 31010:31010 
        - 45678:45678
      volumes:
        - dremio:/opt/dremio/data
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

  nessie:
      image: projectnessie/nessie:0.67.0
      container_name: nessie
      ports:
        - 19120:19120
      environment:
        - QUARKUS_OPENTELEMETRY_ENABLED=false
volumes: 
  dremio: